name: studentmanager
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  leancloud_storage: ^0.2.7
  flutter_screenutil: ^1.0.2
  url_launcher: ^5.4.5
  shared_preferences: ^0.5.8
  fluttertoast: ^4.0.0
  flutter_easyloading: ^1.1.3
  flutter_spinkit: "^4.1.2"
  connectivity: ^0.4.8+6
  flare_flutter: ^2.0.3
  transparent_image: ^1.0.0
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1
  flutter_easyrefresh: ^2.1.1
  pull_to_refresh: ^1.5.7
  liquid_pull_to_refresh: ^2.0.0
  flutter_fadein: ^1.1.1
  fade: ^1.0.0
  fab_circular_menu: ^1.0.0
  curved_navigation_bar: ^0.3.2
  flutter_svg: ^0.17.0
  jpush_flutter:
    git:
      url: git://github.com/jpush/jpush-flutter-plugin.git
      ref: master
  http: ^0.12.1
  dio: ^3.0.9
  beauty_textfield: ^0.0.1
  flip_card: ^0.4.4
  nima: ^1.0.5
  flutter_week_view: ^0.3.1
  intl: ^0.16.1
  flutter_datetime_picker: ^1.3.8
  flutter_picker: ^1.1.5
  permission_handler: ^5.0.1+1
  pin_input_text_field: ^3.0.4
  uuid: ^2.2.0
  animated_widgets: ^1.0.6
  flutter_staggered_grid_view: ^0.3.2
  search_page: ^1.3.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo3.png"

flutter_launcher_name:
  name: "iMusic"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/image_01.png
    - assets/images/image_02.jpg
    - assets/images/image_04.jpg
    - assets/images/image_03.jpg
    - assets/images/logo.png
    - assets/images/wechatQR.jpg
    - assets/images/logo4.png
    - assets/animation/rest.flr
    - assets/animation/123.flr
    - assets/animation/switch.flr
    - assets/animation/wait.flr
    - assets/animation/yes.flr
    - assets/images/icon-710x599-android.png
    - assets/images/classroom.svg
    - assets/images/book.svg
    - assets/images/trophy.svg
    - assets/images/science.svg
    - assets/images/language.svg
    - assets/images/flask.svg
    - assets/images/preview.png
    - assets/images/preview1.png
    - assets/images/preview2.png
    - assets/images/girl1.jpg
    - assets/animation/bihu.nma
    - assets/animation/bihu.png
    - assets/animation/newton.nma
    - assets/animation/newton.png
    - assets/images/boy1.jpg
    - assets/images/boy2.jpg
    - assets/images/boy3.jpg
    - assets/images/girl2.jpg
    - assets/images/girl3.jpg
    - assets/images/logo3.png
    - assets/images/female.svg
    - assets/images/male.svg
    - assets/images/valentine_-love-gender-symbol-sex.svg
    - assets/animation/delete.flr
    - assets/animation/elephant.flr

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/cutie.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/cutie.ttf

    - family: wechat
      fonts:
        - asset: assets/fonts/iconfont.ttf

    - family: msg
      fonts:
        - asset: assets/fonts/iconfont1.ttf

    - family: call
      fonts:
        - asset: assets/fonts/iconfont2.ttf

    - family: email
      fonts:
        - asset: assets/fonts/iconfont3.ttf

    - family: studentpage
      fonts:
        - asset: assets/fonts/custom_icons.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: false
